### ISSUE TITLE
can't import database

### ISSUE THREAD

**Issue by cirnatdan** [pepite/play--database#8]
Hello, 

play db:import fails when I try to import a database. It's probably a Hibernate bug anyway, but any ideas on how I can skip this?

```
14:28:05,919 WARN  ~ Rev.eng. strategy did not report any primary key columns for tariffs_view
Exception in thread "main" java.lang.NoSuchMethodError: org.hibernate.mapping.SimpleValue.<init>(Lorg/hibernate/mapping/Table;)V
    at org.hibernate.cfg.JDBCBinder.bindColumnToSimpleValue(JDBCBinder.java:589)
    at org.hibernate.cfg.JDBCBinder.bindPrimaryKeyToProperties(JDBCBinder.java:443)
    at org.hibernate.cfg.JDBCBinder.createPersistentClasses(JDBCBinder.java:174)
    at org.hibernate.cfg.JDBCBinder.readFromDatabase(JDBCBinder.java:91)
    at org.hibernate.cfg.JDBCMetaDataConfiguration.readFromJDBC(JDBCMetaDataConfiguration.java:40)
    at play.modules.db.Importer.main(Importer.java:164)

```

**Comment by cirnatdan** [comment]
Initially closed, but bug still present.

**Comment by AsemRadhwi** [comment]
Hey, I have the same issue. I'm using the play-1.2.3 and the db-1.1.1 module. Any workaround?

**Comment by robin-drexler** [comment]
+1

**Comment by zarkosusnjar** [comment]
+1 also tried play 1.1 and version db 1.1.1
